---
- name: Install apt repo
  tags: 1password
  become: true
  ansible.builtin.import_tasks:
    file: apt.yml

- name: Install 1password
  tags: 1password
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: 1password
    state: present
  when: not (onepassword_skip_install | default(false))
