---
namespace: compscidr
name: onepassword
authors:
    - Jason Ernst <ernstjason1@gmail.com>
description: Installs 1password and 1password cli
license_file: LICENSE
readme: README.md
version: 0.0.2
repository: https://github.com/compscidr/ansible-1password
tags:
    - onepassword
    - cli
    - tools
