---
- name: Install 1Password Chrome extension support on Debian/Ubuntu
  tags: 1password_chrome
  become: true
  ansible.builtin.apt:
    name: 1password
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure 1Password Chrome native messaging host is present on Debian/Ubuntu
  tags: 1password_chrome
  ansible.builtin.stat:
    path: /opt/1Password/1Password-BrowserSupport
  register: browser_support_debian
  when: ansible_os_family == "Debian"

- name: Verify 1Password Chrome support on Debian/Ubuntu
  tags: 1password_chrome
  ansible.builtin.debug:
    msg: "1Password browser support is installed. Users can install the Chrome extension from the Chrome Web Store: https://chrome.google.com/webstore/detail/1password/aeblfdkhhhdcdjpifhhbdiojplfjncoa"
  when: ansible_os_family == "Debian" and browser_support_debian.stat.exists

- name: Install 1Password on macOS for Chrome support
  tags: 1password_chrome
  community.general.homebrew_cask:
    name: 1password
    state: present
  when: ansible_os_family == "Darwin"

- name: Verify 1Password Chrome support on macOS
  tags: 1password_chrome
  ansible.builtin.debug:
    msg: "1Password is installed. Users can install the Chrome extension from the Chrome Web Store: https://chrome.google.com/webstore/detail/1password/aeblfdkhhhdcdjpifhhbdiojplfjncoa"
  when: ansible_os_family == "Darwin"
