---
- name: Install 1Password Chrome extension support on Debian/Ubuntu
  tags: 1password_chrome
  become: true
  ansible.builtin.apt:
    name: 1password
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure 1Password Chrome native messaging host is present on Debian/Ubuntu
  tags: 1password_chrome
  ansible.builtin.stat:
    path: /opt/1Password/1Password-BrowserSupport
  register: browser_support_debian
  when: ansible_os_family == "Debian"

- name: Create Chrome managed policies directory on Debian/Ubuntu
  tags: 1password_chrome
  become: true
  ansible.builtin.file:
    path: /etc/opt/chrome/policies/managed
    state: directory
    mode: '0755'
  when: ansible_os_family == "Debian"

- name: Install 1Password Chrome extension via policy on Debian/Ubuntu
  tags: 1password_chrome
  become: true
  ansible.builtin.copy:
    content: |
      {
        "ExtensionInstallForcelist": [
          "aeblfdkhhhdcdjpifhhbdiojplfjncoa;https://clients2.google.com/service/update2/crx"
        ]
      }
    dest: /etc/opt/chrome/policies/managed/1password.json
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Install 1Password on macOS for Chrome support
  tags: 1password_chrome
  community.general.homebrew_cask:
    name: 1password
    state: present
  when: ansible_os_family == "Darwin"

- name: Create Chrome managed policies directory on macOS
  tags: 1password_chrome
  become: true
  ansible.builtin.file:
    path: /Library/Google/Chrome/NativeMessagingHosts
    state: directory
    mode: '0755'
  when: ansible_os_family == "Darwin"

- name: Install 1Password Chrome extension via policy on macOS
  tags: 1password_chrome
  become: true
  ansible.builtin.copy:
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>ExtensionInstallForcelist</key>
        <array>
          <string>aeblfdkhhhdcdjpifhhbdiojplfjncoa;https://clients2.google.com/service/update2/crx</string>
        </array>
      </dict>
      </plist>
    dest: /Library/Managed Preferences/com.google.Chrome.plist
    mode: '0644'
  when: ansible_os_family == "Darwin"
