---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-24.04
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  playbooks:
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
