---
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      allow_broken_conditionals: true
  env:
    ANSIBLE_ROLES_PATH: ../../roles
    ANSIBLE_HOST_KEY_CHECKING: false
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_connection: local
  playbooks:
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible