---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if 1password package is installed
      ansible.builtin.command:
        cmd: dpkg -l 1password
      register: onepassword_package_check
      changed_when: false
      failed_when: onepassword_package_check.rc != 0

    - name: Check if 1password-cli package is installed
      ansible.builtin.command:
        cmd: dpkg -l 1password-cli
      register: onepassword_cli_package_check
      changed_when: false
      failed_when: onepassword_cli_package_check.rc != 0

    - name: Verify 1password package installation
      ansible.builtin.debug:
        msg: "1Password package is correctly installed"
      when: onepassword_package_check.rc == 0

    - name: Verify 1password-cli package installation
      ansible.builtin.debug:
        msg: "1Password CLI package is correctly installed"
      when: onepassword_cli_package_check.rc == 0

    - name: Check if op command is available
      ansible.builtin.command:
        cmd: which op
      register: op_command_check
      changed_when: false
      failed_when: op_command_check.rc != 0

    - name: Verify op command is available
      ansible.builtin.debug:
        msg: "1Password CLI (op) command is available at {{ op_command_check.stdout }}"
      when: op_command_check.rc == 0

    - name: Check if browser support exists
      ansible.builtin.stat:
        path: /opt/1Password/1Password-BrowserSupport
      register: browser_support_check

    - name: Verify browser support installation
      ansible.builtin.debug:
        msg: "1Password browser support is installed for Chrome and Firefox extensions"
      when: browser_support_check.stat.exists

    - name: Fail if browser support is not installed
      ansible.builtin.fail:
        msg: "1Password browser support is not installed"
      when: not browser_support_check.stat.exists

    - name: Check if Chrome policy file exists
      ansible.builtin.stat:
        path: /etc/opt/chrome/policies/managed/1password.json
      register: chrome_policy_check

    - name: Verify Chrome extension policy is installed
      ansible.builtin.debug:
        msg: "Chrome extension policy file is installed"
      when: chrome_policy_check.stat.exists

    - name: Fail if Chrome policy is not installed
      ansible.builtin.fail:
        msg: "Chrome extension policy file is not installed"
      when: not chrome_policy_check.stat.exists

    - name: Read Chrome policy file
      ansible.builtin.slurp:
        src: /etc/opt/chrome/policies/managed/1password.json
      register: chrome_policy_content

    - name: Parse Chrome policy JSON
      ansible.builtin.set_fact:
        chrome_policy_json: "{{ chrome_policy_content['content'] | b64decode | from_json }}"

    - name: Verify Chrome policy has correct structure
      ansible.builtin.assert:
        that:
          - chrome_policy_json.ExtensionSettings is defined
          - chrome_policy_json.ExtensionSettings['aeblfdkhhhdcdjpifhhbdiojplfjncoa'] is defined
          - chrome_policy_json.ExtensionSettings['aeblfdkhhhdcdjpifhhbdiojplfjncoa'].installation_mode == 'normal_installed'
          - chrome_policy_json.ExtensionSettings['aeblfdkhhhdcdjpifhhbdiojplfjncoa'].update_url is defined
        fail_msg: "Chrome policy does not have correct structure for 1Password extension"
        success_msg: "Chrome policy correctly configured for 1Password extension auto-installation"

    - name: Check if Firefox policy file exists
      ansible.builtin.stat:
        path: /etc/firefox/policies/policies.json
      register: firefox_policy_check

    - name: Verify Firefox extension policy is installed
      ansible.builtin.debug:
        msg: "Firefox extension policy file is installed"
      when: firefox_policy_check.stat.exists

    - name: Fail if Firefox policy is not installed
      ansible.builtin.fail:
        msg: "Firefox extension policy file is not installed"
      when: not firefox_policy_check.stat.exists

    - name: Read Firefox policy file
      ansible.builtin.slurp:
        src: /etc/firefox/policies/policies.json
      register: firefox_policy_content

    - name: Parse Firefox policy JSON
      ansible.builtin.set_fact:
        firefox_policy_json: "{{ firefox_policy_content['content'] | b64decode | from_json }}"

    - name: Verify Firefox policy has correct structure
      ansible.builtin.assert:
        that:
          - firefox_policy_json.policies is defined
          - firefox_policy_json.policies.ExtensionSettings is defined
          - firefox_policy_json.policies.ExtensionSettings['{d634138d-c276-4fc8-924b-40a0ea21d284}'] is defined
          - firefox_policy_json.policies.ExtensionSettings['{d634138d-c276-4fc8-924b-40a0ea21d284}'].installation_mode == 'normal_installed'
          - firefox_policy_json.policies.ExtensionSettings['{d634138d-c276-4fc8-924b-40a0ea21d284}'].install_url is defined
        fail_msg: "Firefox policy does not have correct structure for 1Password extension"
        success_msg: "Firefox policy correctly configured for 1Password extension auto-installation"

    # Install browsers for headless testing
    - name: Install Chrome dependencies
      ansible.builtin.apt:
        name:
          - wget
          - gnupg
        state: present
        update_cache: true
      become: true

    - name: Add Chrome GPG key
      ansible.builtin.shell:
        cmd: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      become: true
      register: chrome_key
      changed_when: chrome_key.rc == 0
      failed_when: false

    - name: Add Chrome repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome
      become: true
      failed_when: false

    - name: Install Google Chrome
      ansible.builtin.apt:
        name: google-chrome-stable
        state: present
        update_cache: true
      become: true
      register: chrome_install
      failed_when: false

    - name: Install Firefox
      ansible.builtin.apt:
        name: firefox
        state: present
        update_cache: true
      become: true
      register: firefox_install
      failed_when: false

    # Test Chrome extension installation with headless browser
    - name: Create Chrome test profile directory
      ansible.builtin.file:
        path: /tmp/chrome-test-profile
        state: directory
        mode: '0755'
      when: chrome_install is success

    - name: Launch Chrome headless to trigger extension installation (first run)
      ansible.builtin.shell:
        cmd: |
          google-chrome --headless --disable-gpu --no-sandbox --user-data-dir=/tmp/chrome-test-profile --dump-dom about:blank > /tmp/chrome-output.log 2>&1 &
          CHROME_PID=$!
          sleep 30
          kill $CHROME_PID 2>/dev/null || true
          sleep 2
      register: chrome_headless_first
      when: chrome_install is success
      changed_when: false

    - name: Check Chrome output logs
      ansible.builtin.shell:
        cmd: cat /tmp/chrome-output.log 2>/dev/null || echo "No log file"
      register: chrome_logs
      when: chrome_install is success
      changed_when: false
      failed_when: false

    - name: Display Chrome logs for debugging
      ansible.builtin.debug:
        msg: "Chrome logs: {{ chrome_logs.stdout_lines | default(['No logs']) }}"
      when: chrome_install is success

    - name: Wait for extension download
      ansible.builtin.pause:
        seconds: 15
      when: chrome_install is success

    - name: Launch Chrome headless again to ensure extension loads
      ansible.builtin.shell:
        cmd: |
          google-chrome --headless --disable-gpu --no-sandbox --user-data-dir=/tmp/chrome-test-profile --dump-dom about:blank > /tmp/chrome-output2.log 2>&1 &
          CHROME_PID=$!
          sleep 30
          kill $CHROME_PID 2>/dev/null || true
          sleep 2
      register: chrome_headless_second
      when: chrome_install is success
      changed_when: false

    - name: Check for Chrome extension directory
      ansible.builtin.shell:
        cmd: |
          find /tmp/chrome-test-profile -type d -name "*aeblfdkhhhdcdjpifhhbdiojplfjncoa*" | head -1
      register: chrome_extension_dir
      when: chrome_install is success
      changed_when: false
      failed_when: false

    - name: Check Chrome Extensions directory
      ansible.builtin.find:
        paths: /tmp/chrome-test-profile
        patterns: "*aeblfdkhhhdcdjpifhhbdiojplfjncoa*"
        recurse: true
        file_type: any
      register: chrome_ext_files
      when: chrome_install is success

    - name: List Chrome profile contents for debugging
      ansible.builtin.shell:
        cmd: |
          echo "=== Chrome Profile Structure ===" && \
          find /tmp/chrome-test-profile -type f -name "*.json" -o -name "*.crx" -o -name "*1password*" -o -name "*aeblfdkhhhdcdjpifhhbdiojplfjncoa*" | head -20
      register: chrome_profile_debug
      when: chrome_install is success
      changed_when: false
      failed_when: false

    - name: Check Chrome Preferences for extension
      ansible.builtin.shell:
        cmd: |
          if [ -f /tmp/chrome-test-profile/Default/Preferences ]; then
            grep -o "aeblfdkhhhdcdjpifhhbdiojplfjncoa" /tmp/chrome-test-profile/Default/Preferences || echo "Extension ID not found in Preferences"
          else
            echo "Preferences file not found"
          fi
      register: chrome_prefs_check
      when: chrome_install is success
      changed_when: false
      failed_when: false

    - name: Report Chrome extension verification
      ansible.builtin.debug:
        msg: |
          Chrome Extension Verification:
          - Extension directories found: {{ chrome_ext_files.matched | default(0) }}
          - Extension directory: {{ chrome_extension_dir.stdout if chrome_extension_dir.stdout else 'Not found' }}
          - Extension in Preferences: {{ chrome_prefs_check.stdout }}
          - Profile debug info: {{ chrome_profile_debug.stdout_lines | default([]) | join(', ') if chrome_profile_debug.stdout_lines | default([]) | length > 0 else 'No extension files found' }}
      when: chrome_install is success

    # Test Firefox extension installation with headless browser
    - name: Create Firefox test profile directory
      ansible.builtin.file:
        path: /tmp/firefox-test-profile
        state: directory
        mode: '0755'
      when: firefox_install is success

    - name: Launch Firefox headless to trigger extension installation (first run)
      ansible.builtin.shell:
        cmd: |
          firefox --headless --profile /tmp/firefox-test-profile about:blank > /tmp/firefox-output.log 2>&1 &
          FIREFOX_PID=$!
          sleep 30
          kill $FIREFOX_PID 2>/dev/null || true
          pkill -9 firefox 2>/dev/null || true
          sleep 2
      register: firefox_headless_first
      when: firefox_install is success
      changed_when: false

    - name: Check Firefox output logs
      ansible.builtin.shell:
        cmd: cat /tmp/firefox-output.log 2>/dev/null || echo "No log file"
      register: firefox_logs
      when: firefox_install is success
      changed_when: false
      failed_when: false

    - name: Display Firefox logs for debugging
      ansible.builtin.debug:
        msg: "Firefox logs: {{ firefox_logs.stdout_lines | default(['No logs']) }}"
      when: firefox_install is success

    - name: Wait for Firefox extension download
      ansible.builtin.pause:
        seconds: 15
      when: firefox_install is success

    - name: Launch Firefox headless again to ensure extension loads
      ansible.builtin.shell:
        cmd: |
          firefox --headless --profile /tmp/firefox-test-profile about:blank > /tmp/firefox-output2.log 2>&1 &
          FIREFOX_PID=$!
          sleep 30
          kill $FIREFOX_PID 2>/dev/null || true
          pkill -9 firefox 2>/dev/null || true
          sleep 2
      register: firefox_headless_second
      when: firefox_install is success
      changed_when: false

    - name: Check for Firefox extension in profile
      ansible.builtin.find:
        paths: /tmp/firefox-test-profile
        patterns: "*d634138d-c276-4fc8-924b-40a0ea21d284*"
        recurse: true
        file_type: any
      register: firefox_ext_files
      when: firefox_install is success

    - name: List Firefox profile contents for debugging
      ansible.builtin.shell:
        cmd: |
          echo "=== Firefox Profile Structure ===" && \
          find /tmp/firefox-test-profile -type f -name "*.json" -o -name "*.xpi" -o -name "*1password*" -o -name "*d634138d*" | head -20
      register: firefox_profile_debug
      when: firefox_install is success
      changed_when: false
      failed_when: false

    - name: Check Firefox extensions.json for extension
      ansible.builtin.shell:
        cmd: |
          if [ -f /tmp/firefox-test-profile/extensions.json ]; then
            grep -o "d634138d-c276-4fc8-924b-40a0ea21d284" /tmp/firefox-test-profile/extensions.json || echo "Extension ID not found in extensions.json"
          else
            echo "extensions.json file not found"
          fi
      register: firefox_ext_check
      when: firefox_install is success
      changed_when: false
      failed_when: false

    - name: Report Firefox extension verification
      ansible.builtin.debug:
        msg: |
          Firefox Extension Verification:
          - Extension files found: {{ firefox_ext_files.matched | default(0) }}
          - Extension in extensions.json: {{ firefox_ext_check.stdout }}
          - Profile debug info: {{ firefox_profile_debug.stdout_lines | default([]) | join(', ') if firefox_profile_debug.stdout_lines | default([]) | length > 0 else 'No extension files found' }}
      when: firefox_install is success

    - name: Display verification summary
      ansible.builtin.debug:
        msg: |
          ========================================
          1Password Browser Extension Verification
          ========================================
          
          ✓ Chrome Policy Configuration:
            - Policy file created: {{ chrome_policy_check.stat.exists }}
            - Extension ID: aeblfdkhhhdcdjpifhhbdiojplfjncoa
            - Installation mode: normal_installed (user can uninstall)
            - Update URL: {{ chrome_policy_json.ExtensionSettings['aeblfdkhhhdcdjpifhhbdiojplfjncoa'].update_url }}
            - Headless browser test: {{ 'Chrome installed, extension files found: ' + (chrome_ext_files.matched | default(0) | string) if chrome_install is success else 'Chrome not available for testing' }}
            - Extension verification: {{ 'VERIFIED - Extension installed successfully!' if (chrome_ext_files.matched | default(0) > 0 or 'aeblfdkhhhdcdjpifhhbdiojplfjncoa' in chrome_prefs_check.stdout | default('')) else 'Extension configured via policy (may install on next interactive browser launch)' }}
          
          ✓ Firefox Policy Configuration:
            - Policy file created: {{ firefox_policy_check.stat.exists }}
            - Extension ID: {d634138d-c276-4fc8-924b-40a0ea21d284}
            - Installation mode: normal_installed (user can uninstall)
            - Install URL: {{ firefox_policy_json.policies.ExtensionSettings['{d634138d-c276-4fc8-924b-40a0ea21d284}'].install_url }}
            - Headless browser test: {{ 'Firefox installed, extension files found: ' + (firefox_ext_files.matched | default(0) | string) if firefox_install is success else 'Firefox not available for testing' }}
            - Extension verification: {{ 'VERIFIED - Extension installed successfully!' if (firefox_ext_files.matched | default(0) > 0 or 'd634138d-c276-4fc8-924b-40a0ea21d284' in firefox_ext_check.stdout | default('')) else 'Extension configured via policy (may install on next interactive browser launch)' }}
          
          Note: Extensions are configured to auto-install when browsers launch.
          Headless browser testing with extended timeout validates the installation mechanism.
