---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if 1password package is installed
      ansible.builtin.command:
        cmd: dpkg -l 1password
      register: onepassword_package_check
      changed_when: false
      failed_when: onepassword_package_check.rc != 0

    - name: Check if 1password-cli package is installed
      ansible.builtin.command:
        cmd: dpkg -l 1password-cli
      register: onepassword_cli_package_check
      changed_when: false
      failed_when: onepassword_cli_package_check.rc != 0

    - name: Verify 1password package installation
      ansible.builtin.debug:
        msg: "1Password package is correctly installed"
      when: onepassword_package_check.rc == 0

    - name: Verify 1password-cli package installation
      ansible.builtin.debug:
        msg: "1Password CLI package is correctly installed"
      when: onepassword_cli_package_check.rc == 0

    - name: Check if op command is available
      ansible.builtin.command:
        cmd: which op
      register: op_command_check
      changed_when: false
      failed_when: op_command_check.rc != 0

    - name: Verify op command is available
      ansible.builtin.debug:
        msg: "1Password CLI (op) command is available at {{ op_command_check.stdout }}"
      when: op_command_check.rc == 0

    - name: Check if browser support exists
      ansible.builtin.stat:
        path: /opt/1Password/1Password-BrowserSupport
      register: browser_support_check

    - name: Verify browser support installation
      ansible.builtin.debug:
        msg: "1Password browser support is installed for Chrome and Firefox extensions"
      when: browser_support_check.stat.exists

    - name: Fail if browser support is not installed
      ansible.builtin.fail:
        msg: "1Password browser support is not installed"
      when: not browser_support_check.stat.exists
