---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify roles ran successfully
      ansible.builtin.debug:
        msg: "Ansible roles executed successfully during converge phase"

    - name: Check if role variables are accessible
      ansible.builtin.debug:
        msg: "Testing completed - roles are syntactically correct and executable"