---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if 1password package is installed
      ansible.builtin.command:
        cmd: dpkg -l 1password
      register: onepassword_package_check
      changed_when: false
      failed_when: onepassword_package_check.rc != 0

    - name: Check if 1password-cli package is installed
      ansible.builtin.command:
        cmd: dpkg -l 1password-cli
      register: onepassword_cli_package_check
      changed_when: false
      failed_when: onepassword_cli_package_check.rc != 0

    - name: Verify 1password package installation
      ansible.builtin.debug:
        msg: "1Password package is correctly installed"
      when: onepassword_package_check.rc == 0

    - name: Verify 1password-cli package installation
      ansible.builtin.debug:
        msg: "1Password CLI package is correctly installed"
      when: onepassword_cli_package_check.rc == 0

    - name: Check if op command is available
      ansible.builtin.command:
        cmd: which op
      register: op_command_check
      changed_when: false
      failed_when: op_command_check.rc != 0

    - name: Verify op command is available
      ansible.builtin.debug:
        msg: "1Password CLI (op) command is available at {{ op_command_check.stdout }}"
      when: op_command_check.rc == 0

    - name: Check if browser support exists
      ansible.builtin.stat:
        path: /opt/1Password/1Password-BrowserSupport
      register: browser_support_check

    - name: Verify browser support installation
      ansible.builtin.debug:
        msg: "1Password browser support is installed for Chrome and Firefox extensions"
      when: browser_support_check.stat.exists

    - name: Fail if browser support is not installed
      ansible.builtin.fail:
        msg: "1Password browser support is not installed"
      when: not browser_support_check.stat.exists

    - name: Check if Chrome policy file exists
      ansible.builtin.stat:
        path: /etc/opt/chrome/policies/managed/1password.json
      register: chrome_policy_check

    - name: Verify Chrome extension policy is installed
      ansible.builtin.debug:
        msg: "Chrome extension policy file is installed"
      when: chrome_policy_check.stat.exists

    - name: Fail if Chrome policy is not installed
      ansible.builtin.fail:
        msg: "Chrome extension policy file is not installed"
      when: not chrome_policy_check.stat.exists

    - name: Read Chrome policy file
      ansible.builtin.slurp:
        src: /etc/opt/chrome/policies/managed/1password.json
      register: chrome_policy_content

    - name: Parse Chrome policy JSON
      ansible.builtin.set_fact:
        chrome_policy_json: "{{ chrome_policy_content['content'] | b64decode | from_json }}"

    - name: Verify Chrome policy has correct structure
      ansible.builtin.assert:
        that:
          - chrome_policy_json.ExtensionSettings is defined
          - chrome_policy_json.ExtensionSettings['aeblfdkhhhdcdjpifhhbdiojplfjncoa'] is defined
          - chrome_policy_json.ExtensionSettings['aeblfdkhhhdcdjpifhhbdiojplfjncoa'].installation_mode == 'normal_installed'
          - chrome_policy_json.ExtensionSettings['aeblfdkhhhdcdjpifhhbdiojplfjncoa'].update_url is defined
        fail_msg: "Chrome policy does not have correct structure for 1Password extension"
        success_msg: "Chrome policy correctly configured for 1Password extension auto-installation"

    - name: Check if Firefox policy file exists
      ansible.builtin.stat:
        path: /etc/firefox/policies/policies.json
      register: firefox_policy_check

    - name: Verify Firefox extension policy is installed
      ansible.builtin.debug:
        msg: "Firefox extension policy file is installed"
      when: firefox_policy_check.stat.exists

    - name: Fail if Firefox policy is not installed
      ansible.builtin.fail:
        msg: "Firefox extension policy file is not installed"
      when: not firefox_policy_check.stat.exists

    - name: Read Firefox policy file
      ansible.builtin.slurp:
        src: /etc/firefox/policies/policies.json
      register: firefox_policy_content

    - name: Parse Firefox policy JSON
      ansible.builtin.set_fact:
        firefox_policy_json: "{{ firefox_policy_content['content'] | b64decode | from_json }}"

    - name: Verify Firefox policy has correct structure
      ansible.builtin.assert:
        that:
          - firefox_policy_json.policies is defined
          - firefox_policy_json.policies.ExtensionSettings is defined
          - firefox_policy_json.policies.ExtensionSettings['{d634138d-c276-4fc8-924b-40a0ea21d284}'] is defined
          - firefox_policy_json.policies.ExtensionSettings['{d634138d-c276-4fc8-924b-40a0ea21d284}'].installation_mode == 'normal_installed'
          - firefox_policy_json.policies.ExtensionSettings['{d634138d-c276-4fc8-924b-40a0ea21d284}'].install_url is defined
        fail_msg: "Firefox policy does not have correct structure for 1Password extension"
        success_msg: "Firefox policy correctly configured for 1Password extension auto-installation"

    # Install browsers for headless testing
    - name: Install Chrome dependencies
      ansible.builtin.apt:
        name:
          - wget
          - gnupg
        state: present
        update_cache: true
      become: true

    - name: Add Chrome GPG key
      ansible.builtin.shell:
        cmd: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      become: true
      register: chrome_key
      changed_when: chrome_key.rc == 0
      failed_when: false

    - name: Add Chrome repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome
      become: true
      failed_when: false

    - name: Install Google Chrome
      ansible.builtin.apt:
        name: google-chrome-stable
        state: present
        update_cache: true
      become: true
      register: chrome_install
      failed_when: false

    - name: Install Firefox
      ansible.builtin.apt:
        name: firefox
        state: present
        update_cache: true
      become: true
      register: firefox_install
      failed_when: false

    # Test Chrome extension installation with headless browser
    - name: Create Chrome test profile directory
      ansible.builtin.file:
        path: /tmp/chrome-test-profile
        state: directory
        mode: '0755'
      when: chrome_install is success

    - name: Launch Chrome headless to trigger extension installation
      ansible.builtin.shell:
        cmd: |
          timeout 30 google-chrome --headless --disable-gpu --no-sandbox --user-data-dir=/tmp/chrome-test-profile --dump-dom about:blank > /dev/null 2>&1 || true
      register: chrome_headless
      when: chrome_install is success
      changed_when: false

    - name: Check for Chrome extension in profile
      ansible.builtin.shell:
        cmd: |
          find /tmp/chrome-test-profile -type d -name "*aeblfdkhhhdcdjpifhhbdiojplfjncoa*" | head -1
      register: chrome_extension_found
      when: chrome_install is success
      changed_when: false
      failed_when: false

    - name: Check Chrome Extensions directory
      ansible.builtin.find:
        paths: /tmp/chrome-test-profile
        patterns: "*aeblfdkhhhdcdjpifhhbdiojplfjncoa*"
        recurse: true
        file_type: any
      register: chrome_ext_files
      when: chrome_install is success

    - name: Report Chrome extension verification
      ansible.builtin.debug:
        msg: "Chrome extension {{ 'INSTALLED' if chrome_ext_files.matched | default(0) > 0 else 'NOT FOUND in headless test (may require interactive session)' }}"
      when: chrome_install is success

    # Test Firefox extension installation with headless browser
    - name: Create Firefox test profile directory
      ansible.builtin.file:
        path: /tmp/firefox-test-profile
        state: directory
        mode: '0755'
      when: firefox_install is success

    - name: Launch Firefox headless to trigger extension installation
      ansible.builtin.shell:
        cmd: |
          timeout 30 firefox --headless --profile /tmp/firefox-test-profile about:blank > /dev/null 2>&1 || true
      register: firefox_headless
      when: firefox_install is success
      changed_when: false

    - name: Check for Firefox extension in profile
      ansible.builtin.find:
        paths: /tmp/firefox-test-profile
        patterns: "*d634138d-c276-4fc8-924b-40a0ea21d284*"
        recurse: true
        file_type: any
      register: firefox_ext_files
      when: firefox_install is success

    - name: Report Firefox extension verification
      ansible.builtin.debug:
        msg: "Firefox extension {{ 'INSTALLED' if firefox_ext_files.matched | default(0) > 0 else 'NOT FOUND in headless test (may require interactive session)' }}"
      when: firefox_install is success

    - name: Display verification summary
      ansible.builtin.debug:
        msg: |
          ========================================
          1Password Browser Extension Verification
          ========================================
          
          ✓ Chrome Policy Configuration:
            - Policy file created: {{ chrome_policy_check.stat.exists }}
            - Extension ID: aeblfdkhhhdcdjpifhhbdiojplfjncoa
            - Installation mode: normal_installed (user can uninstall)
            - Update URL: {{ chrome_policy_json.ExtensionSettings['aeblfdkhhhdcdjpifhhbdiojplfjncoa'].update_url }}
            - Headless browser test: {{ 'Chrome installed, extension files: ' + (chrome_ext_files.matched | default(0) | string) if chrome_install is success else 'Chrome not available for testing' }}
          
          ✓ Firefox Policy Configuration:
            - Policy file created: {{ firefox_policy_check.stat.exists }}
            - Extension ID: {d634138d-c276-4fc8-924b-40a0ea21d284}
            - Installation mode: normal_installed (user can uninstall)
            - Install URL: {{ firefox_policy_json.policies.ExtensionSettings['{d634138d-c276-4fc8-924b-40a0ea21d284}'].install_url }}
            - Headless browser test: {{ 'Firefox installed, extension files: ' + (firefox_ext_files.matched | default(0) | string) if firefox_install is success else 'Firefox not available for testing' }}
          
          Note: Extensions are configured to auto-install when browsers launch.
          Headless browser testing validates the installation process.
